name: Check Pull Request

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: install
        run: yarn

      - name: lint/build
        run: yarn build

      - name: test
        run: yarn test:nowatch
        env:
          CI: true
